"""Replay the dated agent-assisted reviews from committed public-source evidence."""
import json,gzip,hashlib
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'data/reports/review-evidence'
sha=lambda b:hashlib.sha256(b).hexdigest()
def archive(name): return json.loads(gzip.decompress((out/name).read_bytes()))
historical=archive('historical-reports.json.gz')
now=datetime.now(timezone.utc).isoformat()
# Independent explicit MLB-name map; no matcher/parser import.
names={'Arizona Diamondbacks':'ARI','Athletics':'ATH','Atlanta Braves':'ATL','Baltimore Orioles':'BAL','Boston Red Sox':'BOS','Chicago Cubs':'CHC','Chicago White Sox':'CWS','Cincinnati Reds':'CIN','Cleveland Guardians':'CLE','Colorado Rockies':'COL','Detroit Tigers':'DET','Houston Astros':'HOU','Kansas City Royals':'KC','Los Angeles Angels':'LAA','Los Angeles Dodgers':'LAD','Miami Marlins':'MIA','Milwaukee Brewers':'MIL','Minnesota Twins':'MIN','New York Mets':'NYM','New York Yankees':'NYY','Philadelphia Phillies':'PHI','Pittsburgh Pirates':'PIT','San Diego Padres':'SD','San Francisco Giants':'SF','Seattle Mariners':'SEA','St. Louis Cardinals':'STL','Tampa Bay Rays':'TB','Texas Rangers':'TEX','Toronto Blue Jays':'TOR','Washington Nationals':'WSH'}
def time(s):return datetime.fromisoformat(s.replace('Z','+00:00'))
corpus=archive('matching-source-corpus.json.gz'); reviewed=[]
for i,x in enumerate(corpus):
 a=x['audit_row'];m=x['historical']['match'];p=x['polymarket']['payload'];k=x['kalshi']['payload'];teams=set(a['reported_participants'])
 games=[g for d in x['mlb']['payload']['dates'] for g in d['games'] if {names.get(g['teams'][s]['team']['name']) for s in ['home','away']}==teams and abs((time(g['gameDate'])-time(m['start_utc'])).total_seconds())<=900]
 money=[r for r in p['markets'] if r.get('sportsMarketType')=='moneyline']
 checks={'unique_mlb_fixture':len(games)==1,'kalshi_id':k['event']['event_ticker']==a['kalshi_event_id'],'poly_id':str(p['id'])==str(a['polymarket_event_id']),'single_moneyline':len(money)==1}
 if len(money)==1:
  pm=money[0];outcomes=json.loads(pm['outcomes']);tokens=json.loads(pm['clobTokenIds']);mapping={str(t):names.get(n) for t,n in zip(tokens,outcomes)}
  checks['poly_participants']=set(mapping.values())==teams and len(mapping)==2
  checks['token_team_identity']=all(mapping.get(str(c['token_id']))==c['selected_team'] for c in m['polymarket']['contracts'])
  checks['poly_start_matches_mlb']=len(games)==1 and time(p['startTime'])==time(games[0]['gameDate'])
 kr=k.get('markets') or k['event'].get('markets',[]);checks['kalshi_contract_ids']={r['ticker'] for r in kr}=={r['id'] for r in m['kalshi']['contracts']}
 checks['historical_source_integrity']=sha(historical[x['historical']['path']].encode())==x['historical']['sha256']
 conflict='CONFLICT' in a['status']; game=games[0] if len(games)==1 else {}
 if conflict: checks['makeup_original_date']=game.get('rescheduledFromDate')==a['polymarket_identifier']['date']
 reviewed.append({'kalshi_event_id':a['kalshi_event_id'],'polymarket_event_id':a['polymarket_event_id'],'participants':sorted(teams),'checks':checks,'label':'CORROBORATED_EVENT_IDENTITY' if all(checks.values()) else 'REVIEW_UNRESOLVED','date_conflict':conflict,'mlb_game_pk':game.get('gamePk'),'rescheduled_from_date':game.get('rescheduledFromDate'),'sources':{v:x[v]['request_url'] for v in ['kalshi','polymarket','mlb']},'source_archive_index':i,'pricing_eligible':False})
report={'schema_version':1,'generated_at':now,'reviewer':'parent agent directly checking saved public-source captures; child collection timed out before report','method':'EXPLICIT_MLB_TEAM_MAP_AND_EXACT_TOKEN_IDENTITIES_NO_MATCHER_IMPORT','selection':'26 purposeful cases from September 3 automated 294-pair audit: all five conflicts, every twentieth normal audit row, and doubleheader/team-alias strata; earliest stored match for each. Nonrandom and not blind.','sample_count':len(reviewed),'corroborated_count':sum(x['label']=='CORROBORATED_EVENT_IDENTITY' for x in reviewed),'unresolved_count':sum(x['label']!='CORROBORATED_EVENT_IDENTITY' for x in reviewed),'human_independent_precision_gate':'NOT_SATISFIED','exact_decisions_in_sample':0,'precision_claim':'No estimate of population EXACT precision or recall; 26 REVIEW cases are insufficient and not human-independent labels.','source_archive':'review-evidence/matching-source-corpus.json.gz','source_archive_sha256':sha((out/'matching-source-corpus.json.gz').read_bytes()),'records':reviewed,'pricing_eligible':False}
(ROOT/'data/reports/matching-independent-review.json').write_text(json.dumps(report,indent=2)+'\n')
rows=['# Matching review — 6 September 2026','','**Agent-assisted official-source corroboration, not a human-independent precision release gate.**','',report['selection'],'',f"Result: {report['corroborated_count']}/{report['sample_count']} sampled event identities corroborated; {report['unresolved_count']} unresolved. No EXACT decisions were sampled, so zero demonstrated mismatches here is not a 99% EXACT precision claim. Recall was not measured.",'','Every case was checked against a unique official MLB fixture by participant names and start, source event IDs, exact token-to-team identities, contract IDs, and the hash of its immutable historical source report. The five conflicts additionally matched MLB rescheduledFromDate to the older Polymarket slug date. Parent separately refetched all five MLB schedules.','', '| Kalshi fixture | MLB gamePk | Label |','|---|---:|---|']
rows += [f"| {r['kalshi_event_id']} | {r['mlb_game_pk']} | {r['label']} |" for r in reviewed]
rows += ['','## Code defects fixed and limits','','Reverse ambiguity now rejects two Kalshi fixtures competing for one Polymarket fixture. Malformed binary arrays and duplicate token IDs are rejected. Fractional time differences are compared before integer conversion. Existing small-page traversal preserves the bounded catalog and fails on cursor loops. Regression tests exercise each case; no eligibility logic was relaxed.','','The production source-identifier audit remains conservative: all five slug-date discrepancies stay quarantined in resolution counts, despite evidence-level makeup corroboration. A review override requires a separately versioned provenance policy, not an ad hoc bypass.','','Sources, per-check results and preserved raw captures: [review JSON](../data/reports/matching-independent-review.json). Reviewers timed out; their partial source collection was re-read and evaluated by the parent, not accepted as a completed independent sign-off.']
(ROOT/'docs/matching-independent-review.md').write_text('\n'.join(rows)+'\n')
sources=archive('settlement-source-corpus.json.gz'); assert all(x['http_status']=='200' for x in sources)
by={x['id']:x for x in sources}; live=json.loads(historical['data/shadow/20260906T045510Z.json']);records=[]
for m in live['matches']:
 ks=[by[c['id']] for c in m['kalshi']['contracts']]; ps=by['poly_'+m['polymarket']['event_id']]; pe=ps['payload'][0]; pm=[x for x in pe['markets'] if x.get('sportsMarketType')=='moneyline']; assert len(pm)==1
 kt=[x['payload']['market']['rules_secondary'] for x in ks];pt=pm[0]['description']
 mismatch=all('over two days' in t and 'fair price' in t for t in kt) and 'remain open until the game has been completed' in pt and '50-50' in pt
 records.append({'kalshi_event_id':m['kalshi']['event_id'],'polymarket_event_id':m['polymarket']['event_id'],'verdict':'NON_EQUIVALENT_EXCEPTIONAL_RULES' if mismatch else 'UNRESOLVED_REVIEW','kalshi_rule_excerpt':kt[0],'polymarket_rule_excerpt':pt,'source_urls':[x['url'] for x in ks]+[ps['url']],'pricing_eligible':False})
settlement={'schema_version':1,'generated_at':now,'review_type':'PARENT_AGENT_SOURCE_REVIEW_NOT_OWNER_OR_LEGAL_SIGN_OFF','scope_snapshot':'data/shadow/20260906T045510Z.json','snapshot_sha256':sha(historical['data/shadow/20260906T045510Z.json'].encode()),'source_fetch_count':len(sources),'http_200_count':len(sources),'matched_event_count':len(records),'non_equivalent_count':sum(r['verdict']=='NON_EQUIVALENT_EXCEPTIONAL_RULES' for r in records),'eligible_subset':[],'verdict':'NO_GO_CROSS_VENUE_MLB_GUARANTEED_PAYOUT','source_archive':'review-evidence/settlement-source-corpus.json.gz','source_archive_sha256':sha((out/'settlement-source-corpus.json.gz').read_bytes()),'binding_terms_url':by['kalshi_series']['payload']['series']['contract_terms_url'],'binding_terms_file':'review-evidence/MLBGAME.pdf','binding_terms_sha256':sha((out/'MLBGAME.pdf').read_bytes()),'fee_evidence':{'kalshi_series_fee_type':by['kalshi_series']['payload']['series']['fee_type'],'kalshi_series_multiplier':by['kalshi_series']['payload']['series']['fee_multiplier'],'warning':'Series metadata is not a historical/per-event all-cost fee model; inspect event overrides. No eligible net-result population.'},'records':records,'pricing_eligible':False}
(ROOT/'data/reports/settlement-eligibility-review.json').write_text(json.dumps(settlement,indent=2)+'\n')
print(json.dumps({'matching_sample':len(reviewed),'corroborated':report['corroborated_count'],'unresolved':[r for r in reviewed if r['label']!='CORROBORATED_EVENT_IDENTITY'],'settlement_events':len(records),'non_equivalent':settlement['non_equivalent_count']},indent=2))
